server:
  port: 8085
spring:
  application:
    name: user-service #服务名称
  datasource: #数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.87.117.192:3306/b2c?useUnicode=true&characterEncoding=utf8
    username: root
    password: Qq123123
  redis: #通过redis用于测试session的共享
    host: 58.87.117.192
    port: 6379
    password:
eureka: #eureka注册服务客户端
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance: #实例,情况
    prefer-ip-address: true
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${eureka.instance.ip-address}.${server.port} #把服务注册进中心;注册名默认是“IP名:应用名:应用端口名”
    lease-renewal-interval-in-seconds: 3 # 每隔3秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期