server:
  port: 8089

spring:
  application:
    name: order-service #服务名称
  datasource:  #数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.87.117.192:3306/b2c?useUnicode=true&characterEncoding=utf8
    username: root
    password: Qq123123
    druid: #连接池
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  rabbitmq: #消息队列
    host: 58.87.117.192
    username: b2c
    password: Qwertyuiop
    virtual-host: b2c
    template: #静态网页技术
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: b2c.item.exchange
    publisher-confirms: true
  redis:
    host: 58.87.117.192
eureka: #eureka注册服务客户端
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${eureka.instance.ip-address}.${server.port} #把服务注册进中心;注册名默认是“IP名:应用名:应用端口名”
    lease-renewal-interval-in-seconds: 3 # 每隔3秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

mybatis:
  type-aliases-package: com.mr.item.pojo
  mapper-locations: mapper/OrderMapper.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰功能
mapper:
  not-empty: false #设置true以后，会去判断 insert 和 update 中字符串类型!=’’
  identity: mysql #指定是mysql数据库
b2c:
  worker: #生成订单id,雪花算法
    workerId: 1
    datacenterId: 1
  jwt:
    pubKeyPath: E:/1908-java-wuyue/idea-workspace/reskey-rsa/rea.pub # 公钥地址
    cookieName: B2C_TOKEN # cookie的名称
